# Generated by Django 2.1.2 on 2018-10-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=150)),
                ('plainTextPassword', models.CharField(max_length=150)),
                ('passwordHash', models.CharField(max_length=512)),
                ('created', models.BooleanField(default=True)),
                ('dateOfCreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
